
import java.awt.List;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Collections;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author selcu
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    ArrayList<Double> arr = new ArrayList<>();
    int sayac = 0;

    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        veriGirisi = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        sayici = new javax.swing.JLabel();
        degerlerText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        modCevap = new javax.swing.JTextField();
        aritmatikCevap = new javax.swing.JTextField();
        medyanCevap = new javax.swing.JTextField();
        varyansText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        standartsapmaText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        omsText = new javax.swing.JTextField();
        q1Text = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        q3Text = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dkText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setText("Veri : ");

        jButton2.setText("Gir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Hesapla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Aritmatik Ort.");

        jLabel3.setText("Medyan");

        jLabel4.setText("Mod");

        jLabel5.setText("Varyans");

        jLabel6.setText("Standart Sapma");

        jLabel7.setText("OMS");

        jLabel8.setText("Q1");

        jLabel9.setText("Q3");

        jLabel10.setText("Değişim Katsayısı");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(omsText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                .addComponent(aritmatikCevap, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(medyanCevap, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(modCevap, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(varyansText, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel8))
                                    .addComponent(q1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel9))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(q3Text, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(dkText, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(degerlerText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(veriGirisi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(71, 71, 71)
                                .addComponent(sayici, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addGap(58, 58, 58))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(standartsapmaText, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel4)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel5)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel6)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veriGirisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(sayici, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(degerlerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aritmatikCevap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medyanCevap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modCevap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varyansText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(standartsapmaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(q1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(q3Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dkText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(omsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        sayac++;
        sayici.setText(String.valueOf(sayac));

        //   int rasgele = (int) (Math.random() * 20);
        //     veriGirisi.setText(String.valueOf(rasgele));
        double giris = Double.valueOf(veriGirisi.getText());
        arr.add(giris);

        degerlerText.setText(arr.toString());

        veriGirisi.setText("");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        // aritmatik ortalama
        int arrSize = arr.size();
        int aritmatikOrt = 0;

        for (double i : arr) {

            aritmatikOrt += i;

        }

        aritmatikOrt = (aritmatikOrt / arrSize);

        aritmatikCevap.setText(String.valueOf(aritmatikOrt));

        // mod
        ArrayList<Double> bakildimi = new ArrayList<>();
        int tempTekrar = 0;
        double tempSayi = 0;
        for (Double i : arr) {

            int a = 0;

            for (Double j : bakildimi) {
                if (i.equals(j)) {
                    a++;
                }
            }

            if (a == 0) {

                int sayiAdedi = 0;

                for (Double t : arr) {
                    if (i.equals(t)) {
                        sayiAdedi++;
                    }
                }

                bakildimi.add(i);

                if (sayiAdedi > tempTekrar) {
                    tempTekrar = sayiAdedi;
                    tempSayi = i;
                }

            }
        }

        modCevap.setText(String.valueOf(tempSayi));

        // medyan
        ArrayList<Double> medyanAr = new ArrayList<>();
        for (Double i : arr) {
            medyanAr.add(i);
        }

        int ortanca = (medyanAr.size());

        Collections.sort(medyanAr);

        if (ortanca % 2 == 1) {
            ortanca += 1;
            ortanca /= 2;
            medyanCevap.setText(String.valueOf(medyanAr.get(ortanca - 1)));
        } else {
            int bir = ortanca / 2;
            int iki = ortanca / 2 + 1;
            medyanCevap.setText(String.valueOf(medyanAr.get(bir - 1) + " " + medyanAr.get(iki - 1)));
        }

        // varyans 
        int varyansToplam = 0;
        for (Double i : arr) {
            varyansToplam += (i - aritmatikOrt) * (i - aritmatikOrt);
        }

        varyansToplam = varyansToplam / (arr.size() - 1);
        double varyans = Math.floor(varyansToplam * 100) / 100;

        varyansText.setText(varyans + "");

        standartsapmaText.setText("" + Math.floor(Math.sqrt(varyansToplam) * 100) / 100);

        // oms
        // varyans 
        double omsToplam = 0;
        for (Double i : arr) {
            omsToplam += Math.abs(i - aritmatikOrt);
        }

        omsToplam = omsToplam / (arr.size());

        double oms = Math.floor(omsToplam * 100) / 100;

        omsText.setText("" + oms);

        // q1
        int n = (Integer) arr.size();
        Collections.sort(arr);

        int L = arr.get(n - 1).intValue();
        int S = arr.get(0).intValue();

        int R = L - S;

        double k = Math.sqrt(n);
        k = Math.ceil(k);

        double h = R / k;
        h = Math.ceil(h);

        ArrayList<Integer> alt1 = new ArrayList<>();

        int temp1 = S;
        if (S % temp1 == 0.5) {
            temp1 -= 0.1;
        }
        for (int i = 0; i < k; i++) {
            alt1.add(temp1);
            // altText.append(temp1 + "\n");
            temp1 += h;
        }

        ArrayList<Integer> ust1 = new ArrayList<>();
        int temp2 = alt1.get(1) - 1;
        for (int i = 0; i < k; i++) {
            ust1.add(temp2);
            //  ustText1.append(temp2 + "\n");
            temp2 += h;
        }

        ArrayList<Double> alt2 = new ArrayList<>();
        double temp3 = alt1.get(0) - 0.5;
        for (int i = 0; i < k; i++) {
            alt2.add(temp3);
            // alt2Text.append(temp3 + "\n");
            temp3 += h;
        }

        ArrayList<Double> ust2 = new ArrayList<>();
        double temp4 = alt2.get(1);
        for (int i = 0; i < k; i++) {
            ust2.add(temp4);
            //    ust2Text.append(temp4 + "\n");
            temp4 += h;
        }

        // altText.append(Arrays.toString(arr));
        ArrayList<Double> frekans = new ArrayList<>();
        double s = 0;
        for (int i = 0; i < k; i++) {
            for (int j = 0; j < n; j++) {
                if (arr.get(j) > alt2.get(i) && arr.get(j) < ust2.get(i)) {
                    s++;
                }

            }
            frekans.add(s);
            //     frekansText.append((int) s + "\n");

            s = 0;
        }

        // q1 start
        double Q1=0;
        double j1=0;
        double L1=0;
        double fQ1=0;
        int i=0;
        double y=(double)n/4;
        double n1=0;
        
        while(n1 < y)
        {
            n1+=frekans.get(i);
            i++;
        }
        n1-=frekans.get(i-1);
        j1=y-n1;
        
        int d1=0;
        for(int c=0;c<k;c++){
            
            d1+=frekans.get(c);
            if(d1 >  y){
                
                L1=alt2.get(c);
                fQ1=frekans.get(c);
                break;
            }
        }
        
        Q1=L1+((j1*h)/fQ1);
        
        q1Text.setText(new DecimalFormat("##.##").format(Q1));
        

         
        double Q3=0;
        double j3=0;
        double L3=0;
        double fQ3=0; 
        
      
       double z=(double)(n/4.0)*3.0;
       
        int r=0;
        double n3=0;
        
        while(n3 <  z)
        {
            n3+=frekans.get(r);
            r++;
        }
        
        n3-=frekans.get(r-1);
        j3=z-n3;
        
        int d3=0;
        for(int f=0;f<k;f++){
            d3+=frekans.get(f);
            
            if(d3 >  z){
                
                L3=alt2.get(f);
                fQ3=frekans.get(f);
                break;
            }
        }
        
        Q3=L3+((j3*h)/fQ3);
        
        q3Text.setText(new DecimalFormat("##.##").format(Q3));


        // dk
        
        dkText.setText(""+(Math.floor(Math.sqrt(varyansToplam) * 100) / 100/aritmatikOrt));
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aritmatikCevap;
    private javax.swing.JTextField degerlerText;
    private javax.swing.JTextField dkText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField medyanCevap;
    private javax.swing.JTextField modCevap;
    private javax.swing.JTextField omsText;
    private javax.swing.JTextField q1Text;
    private javax.swing.JTextField q3Text;
    private javax.swing.JLabel sayici;
    private javax.swing.JTextField standartsapmaText;
    private javax.swing.JTextField varyansText;
    private javax.swing.JTextField veriGirisi;
    // End of variables declaration//GEN-END:variables
}
